### ISSUE TITLE
Make video controls / buttons darken on hover

### ISSUE THREAD

**Issue by peepopoggers** [dragosnfy/FreeTube#2]
![image](https://user-images.githubusercontent.com/72892531/124368707-91222200-dc5b-11eb-902f-57d74ced7730.png)

**Comment by dragosnfy** [comment]
Generally they should be lighter on hover, but I get you! There definitely needs to be some effect when people hover on them! Or use the main color maybe. Thanks! I'm on it next!

**Comment by peepopoggers** [comment]
yeah, try lighter

**Comment by dragosnfy** [comment]
Fixed! You'll see it in the next release!
