### ISSUE TITLE
Add padding to top and bottom to comment expand link & misc

### ISSUE THREAD

**Issue by peepopoggers** [dragosnfy/FreeTube#3]
![image](https://user-images.githubusercontent.com/72892531/124368735-e9f1ba80-dc5b-11eb-8c89-cb9c9bef1ff2.png)

This could be a bit taller, no underline.
Also background would darken on hover.

**Comment by dragosnfy** [comment]
Damn! I like your suggestions 🔥🔥🔥 I'll do this one as well!

**Comment by peepopoggers** [comment]
Lighter on hover btw

**Comment by dragosnfy** [comment]
Fixed!

**Comment by dragosnfy** [comment]
Changing the background of the button changes the whole comments' background, so right now that can't be implemented but it could in the future. However this is basically partially fixed
