### ISSUE TITLE
Make the text selection color the same color as the main color and the selected text color to the the theme color

### ISSUE THREAD

**Issue by jurapura13** [dragosnfy/FreeTube#9]
Not to be nitpicky but I have a suggestion that is very simple to implement: Make the text selection color the same color as the main color and the selected text color to the the theme color; e.g. in my case (Dark theme with Deep Orange) it would be: 
::selection {
  color: black;
  background: #ff571c; //Deep Orange
}
Just hook it up to some variables and voila!

**Comment by dragosnfy** [comment]
fixed, although I'll make the text color change from white to black depending on the accent color & theme.
